services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.107.4   # pin to a known-good version
    container_name: n8n
    restart: always
    # Bind to loopback only so it’s not exposed to your LAN
    ports:
      - "127.0.0.1:5678:5678"
    env_file:
      - .env
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - NODE_ENV=production
      - GENERIC_TIMEZONE=${GENERIC_TIMEZONE}
      - TZ=${GENERIC_TIMEZONE}
      # These mirror what you put in .env; keeping explicit for clarity.
      - N8N_HOST=${N8N_HOST}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${WEBHOOK_URL}
      # (optional hardening)
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_PUBLIC_API_DISABLED=true
    volumes:
      - n8n_data:/home/node/.n8n       # DB + encryption key (PERSIST THIS!)
      - ./local-files:/files           # your host <-> n8n file share

volumes:
  n8n_data:
