services:
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    restart: unless-stopped
    ports:
      - "3000:3000"
    env_file: .env
    volumes:
      - /home/josh/docker/homepage:/app/config
      - /var/run/docker.sock:/var/run/docker.sock