---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/services/

- Networking:
    - Firewall:
        icon: sophos.png
        href: https://192.168.50.1:4444
        description: Router & Firewall

    - UniFi:
        icon: unifi.png
        href: https://192.168.50.5:8443
        description: Unifi Controller

    - Pi-hole:
        icon: pi-hole.png
        href: https://192.168.50.6/admin
        description: DNS & Ad blocking
        siteMonitor: https://192.168.50.6/admin
        widget:
          type: pihole
          url: https://192.168.50.6
          version: 6                 # REQUIRED for v6+
          #key: <your-app-password>   # v6: use your password or an app password
          fields: ["queries", "blocked", "blocked_percent", "gravity"]

- Infrastructure:
    - Proxmox:
        icon: proxmox.png
        href: https://192.168.60.11:8006
        description: Virtualization host
        ping: 192.168.60.11

    - NAS:
        icon: si-qnap
        href: https://192.168.60.12
        description: Primary NAS
        widget:
          type: qnap
          url: https://192.168.60.12
          username: {{ secrets.qnap_user }}
          password: {{ secrets.qnap_pass }}
          fields: ["cpuUsage", "memUsage", "systemTempC", "poolUsage"]

    - Portainer LXC:
        icon: portainer.png
        href: https://192.168.60.13:9443
        description: Container management
        proxmoxNode: pve
        proxmoxVMID: 300
        proxmoxType: lxc

- Media:
    - Plex:
        icon: plex.png
        href: http://192.168.50.20:32400/web
        description: Media server
        siteMonitor: http://192.168.50.20:32400

- Monitoring:
    - Uptime Kuma:
        icon: uptime-kuma.png
        href: http://192.168.60.13:3001
        descirption: Montioring