---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/

title: Life OS
description: Josh's Homebase

providers:
  openweathermap: openweathermapapikey
  weatherapi: weatherapiapikey
